export const PostTypes = {
  CREATE_POST_LOADING: "CREATE_POST_LOADING",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_ERROR: "CREATE_POST",

  GET_POST: "GET_POST",
  GET_POST_LIST: "GET_POST_LIST",
  EDIT_POST: "EDIT_POST",
  DELETE_POST: "DELETE_POST",
}